apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-api
  endpoints:
    - port: "http"
      path: /metrics
      interval: 30s
