apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: your-flask-app-image:tag
          ports:
            - containerPort: 5000  # Port your Flask app is running on
            - containerPort: 8080  # Port your Flask app exposes metrics on
