apiVersion: v1
kind: Pod
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  containers:
    - name: flask-api
      image: flask-api:latest
      ports:
        - containerPort: 5000
      imagePullPolicy: Never
      resources:
        limits:
          memory: "200Mi"
