apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-api
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
